Area.create(area_name: "北海道")
Area.create(area_name: "青森")
Area.create(area_name: "秋田")
Area.create(area_name: "岩手")
Area.create(area_name: "山形")
Area.create(area_name: "宮城")
Area.create(area_name: "福島")
Area.create(area_name: "新潟")
Area.create(area_name: "富山")
Area.create(area_name: "石川")
Area.create(area_name: "福井")
Area.create(area_name: "岐阜")
Area.create(area_name: "長野")
Area.create(area_name: "山梨")
Area.create(area_name: "静岡")
Area.create(area_name: "愛知")
Area.create(area_name: "群馬")
Area.create(area_name: "栃木")
Area.create(area_name: "茨城")
Area.create(area_name: "埼玉")
Area.create(area_name: "東京")
Area.create(area_name: "神奈川")
Area.create(area_name: "千葉")
Area.create(area_name: "滋賀")
Area.create(area_name: "三重")
Area.create(area_name: "奈良")
Area.create(area_name: "京都")
Area.create(area_name: "大阪")
Area.create(area_name: "兵庫")
Area.create(area_name: "和歌山")
Area.create(area_name: "鳥取")
Area.create(area_name: "岡山")
Area.create(area_name: "広島")
Area.create(area_name: "島根")
Area.create(area_name: "山口")
Area.create(area_name: "香川")
Area.create(area_name: "徳島")
Area.create(area_name: "愛媛")
Area.create(area_name: "高知")
Area.create(area_name: "福岡")
Area.create(area_name: "大分")
Area.create(area_name: "佐賀")
Area.create(area_name: "熊本")
Area.create(area_name: "宮崎")
Area.create(area_name: "鹿児島")
Area.create(area_name: "長崎")
Area.create(area_name: "沖縄")



# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
